-- MySQL Script generated by MySQL Workbench
-- Sun May 28 00:57:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sige_ipial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sige_ipial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sige_ipial` DEFAULT CHARACTER SET utf8 ;
USE `sige_ipial` ;

-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_endereco` (
  `endereco_id` INT NOT NULL AUTO_INCREMENT,
  `municipio` VARCHAR(55) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `zona` VARCHAR(45) NULL,
  `numero casa` INT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `update_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`endereco_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_pessoa` (
  `pessoa_id` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(455) NOT NULL,
  `num_bi` VARCHAR(14) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `gerero_DG` ENUM('Masculino', 'Femenino') NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `update_at` TIMESTAMP NOT NULL,
  `endereco_id` INT NOT NULL,
  PRIMARY KEY (`pessoa_id`, `endereco_id`),
  UNIQUE INDEX `num_bi_UNIQUE` (`num_bi` ASC) VISIBLE,
  INDEX `fk_tbl_pessoa_tbl_endereco1_idx` (`endereco_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_pessoa_tbl_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `sige_ipial`.`tbl_endereco` (`endereco_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_professor` (
  `professor_id` INT NOT NULL AUTO_INCREMENT,
  `formacao` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `update_at` TIMESTAMP NOT NULL,
  `cargo` ENUM('Coordenador', 'Sem cargo') NOT NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`professor_id`, `pessoa_id`),
  INDEX `fk_professores_pessoas1_idx` (`pessoa_id` ASC) VISIBLE,
  CONSTRAINT `fk_professores_pessoas1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `sige_ipial`.`tbl_pessoa` (`pessoa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_area_formacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_area_formacao` (
  `area_formacao_id` INT NOT NULL AUTO_INCREMENT,
  `nome_area_formacao` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `update_at` TIMESTAMP NOT NULL,
  `professor_id` INT NOT NULL,
  PRIMARY KEY (`area_formacao_id`, `professor_id`),
  INDEX `fk_tbl_area_formacao_tbl_professor1_idx` (`professor_id` ASC) VISIBLE)
ENGINE = ARCHIVE;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_curso` (
  `curso_id` INT NOT NULL AUTO_INCREMENT,
  `nome_curso` VARCHAR(455) NOT NULL,
  `sigla` VARCHAR(4) NOT NULL,
  `area_formacao_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `update_at` TIMESTAMP NOT NULL,
  `professor_id` INT NOT NULL,
  PRIMARY KEY (`curso_id`, `area_formacao_id`, `professor_id`),
  INDEX `fk_tbl_curso_tbl_area_formacao1_idx` (`area_formacao_id` ASC) VISIBLE,
  INDEX `fk_tbl_curso_tbl_professor1_idx` (`professor_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_curso_tbl_area_formacao1`
    FOREIGN KEY (`area_formacao_id`)
    REFERENCES `sige_ipial`.`tbl_area_formacao` (`area_formacao_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_curso_tbl_professor1`
    FOREIGN KEY (`professor_id`)
    REFERENCES `sige_ipial`.`tbl_professor` (`professor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_disciplina` (
  `disciplina_id` INT NOT NULL,
  `nome_disciplina` VARCHAR(100) NOT NULL,
  `componente` VARCHAR(100) NOT NULL,
  `tempo_prova` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `update` TIMESTAMP NOT NULL,
  `curso_id` INT NULL,
  PRIMARY KEY (`disciplina_id`),
  INDEX `fk_tbl_disciplina_tbl_curso1_idx` (`curso_id` ASC) VISIBLE,
  UNIQUE INDEX `nome_disciplina_UNIQUE` (`nome_disciplina` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_disciplina_tbl_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `sige_ipial`.`tbl_curso` (`curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_classe` (
  `classe_id` INT NOT NULL AUTO_INCREMENT,
  `classe` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `update_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`classe_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_turma` (
  `id_turma` INT NOT NULL,
  `nome_turma` VARCHAR(10) NOT NULL,
  `classe_id` INT NOT NULL,
  `curso_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `update` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_turma`, `classe_id`, `curso_id`),
  UNIQUE INDEX `nome_turma_UNIQUE` (`nome_turma` ASC) VISIBLE,
  INDEX `fk_tbl_turma_tbl_classe1_idx` (`classe_id` ASC) VISIBLE,
  INDEX `fk_tbl_turma_tbl_curso1_idx` (`curso_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_turma_tbl_classe1`
    FOREIGN KEY (`classe_id`)
    REFERENCES `sige_ipial`.`tbl_classe` (`classe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_turma_tbl_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `sige_ipial`.`tbl_curso` (`curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_sala` (
  `sala_id` INT NOT NULL,
  `sala` INT NULL,
  `tipo_sala` ENUM('Laboratorio', 'Normal') NULL,
  `created_at` TIMESTAMP NOT NULL,
  `update_at` TIMESTAMP NOT NULL,
  `nome_sala` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`sala_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_escola_proveniencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_escola_proveniencia` (
  `escola_proveniencia_id` INT NOT NULL AUTO_INCREMENT,
  `nome_escola` VARCHAR(45) NOT NULL,
  `turno` ENUM('Manhã', 'Tarde', 'Noite') NOT NULL,
  `num_processo` INT NOT NULL,
  `num_aluno` INT NOT NULL,
  `ultimo_anoLectivo` VARCHAR(15) NOT NULL,
  `media` DOUBLE NOT NULL,
  `certificado` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `update` TIMESTAMP NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_ano_lectivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_ano_lectivo` (
  `ano_lectivo_id` INT NOT NULL,
  `ano_lectivo` VARCHAR(15) NOT NULL,
  `status_ano_lectivo` TINYINT NOT NULL,
  `data_inicio_ano_lectivo` DATE NOT NULL,
  `data_fim_ano_ano_lectivo` DATE NOT NULL,
  `num_aluno_na_turma` INT NOT NULL,
  `num_sala_escola` INT(2) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `update_at` TIMESTAMP NOT NULL,
  `data_inicio_inscricao` DATE NOT NULL,
  `data_fim_inscricao` DATE NOT NULL,
  `data_inicio_matricula` DATE NOT NULL,
  `data_fim_matricula` DATE NOT NULL,
  PRIMARY KEY (`ano_lectivo_id`),
  UNIQUE INDEX `tb_ano_lectino_UNIQUE` (`ano_lectivo` ASC) VISIBLE,
  UNIQUE INDEX `data_inicio_ano_lectivo_UNIQUE` (`data_inicio_ano_lectivo` ASC) VISIBLE,
  UNIQUE INDEX `data_fim_ano_ano_lectivo_UNIQUE` (`data_fim_ano_ano_lectivo` ASC) VISIBLE,
  UNIQUE INDEX `data_inicio_inscricao_UNIQUE` (`data_inicio_inscricao` ASC) VISIBLE,
  UNIQUE INDEX `data_fim_inscricao_UNIQUE` (`data_fim_inscricao` ASC) VISIBLE,
  UNIQUE INDEX `data_inicio_matricula_UNIQUE` (`data_inicio_matricula` ASC) VISIBLE,
  UNIQUE INDEX `data_fim_matricula_UNIQUE` (`data_fim_matricula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_candidato` (
  `candidato_id` INT NOT NULL,
  `nome_pai_cand` VARCHAR(255) NOT NULL,
  `nome_mae_cand` VARCHAR(255) NOT NULL,
  `naturalidade_cand` VARCHAR(255) NOT NULL,
  `estado_candidato` ENUM('activo', 'inactivo') NOT NULL,
  `escola_proveniencia_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `update` TIMESTAMP NOT NULL,
  `status` ENUM('Pendente', 'Admitido', 'Não admitido') NOT NULL,
  `pessoa_id` INT NOT NULL,
  `ano_lectivo_id` INT NOT NULL,
  PRIMARY KEY (`candidato_id`, `escola_proveniencia_id`, `pessoa_id`, `ano_lectivo_id`),
  INDEX `fk_tbl_candidato_tbl_escola_proveniencia1_idx` (`escola_proveniencia_id` ASC) VISIBLE,
  INDEX `fk_tbl_candidato_tbl_pessoa1_idx` (`pessoa_id` ASC) VISIBLE,
  INDEX `fk_candidatos_anos_lectivo1_idx` (`ano_lectivo_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_candidato_tbl_escola_proveniencia1`
    FOREIGN KEY (`escola_proveniencia_id`)
    REFERENCES `sige_ipial`.`tbl_escola_proveniencia` (`escola_proveniencia_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_candidato_tbl_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `sige_ipial`.`tbl_pessoa` (`pessoa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_candidatos_anos_lectivo1`
    FOREIGN KEY (`ano_lectivo_id`)
    REFERENCES `sige_ipial`.`tbl_ano_lectivo` (`ano_lectivo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_aluno` (
  `aluno_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `update` TIMESTAMP NOT NULL,
  `curso_id` INT NOT NULL,
  `candidato_id` INT NOT NULL,
  PRIMARY KEY (`aluno_id`, `curso_id`, `candidato_id`),
  INDEX `fk_tbl_aluno_tbl_curso1_idx` (`curso_id` ASC) VISIBLE,
  INDEX `fk_tbl_aluno_tbl_candidato1_idx` (`candidato_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_aluno_tbl_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `sige_ipial`.`tbl_curso` (`curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_aluno_tbl_candidato1`
    FOREIGN KEY (`candidato_id`)
    REFERENCES `sige_ipial`.`tbl_candidato` (`candidato_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_ficha_biografica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_ficha_biografica` (
  `id_fichabiografica` INT NOT NULL,
  `descricao` LONGTEXT NULL,
  `aluno_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `update_at` TIMESTAMP NOT NULL,
  `PAP_nota` DOUBLE NULL,
  `PAP_tema` VARCHAR(100) NULL,
  `PAP_data` DATE NULL,
  `estagio_local` VARCHAR(100) NULL,
  `estagio_nota` DOUBLE NULL,
  `estagio_inicio` DATE NULL,
  `estagio_fim` DATE NULL,
  PRIMARY KEY (`id_fichabiografica`, `aluno_id`),
  INDEX `fk_tbl_fichabiografica_tbl_aluno1_idx` (`aluno_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_fichabiografica_tbl_aluno1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `sige_ipial`.`tbl_aluno` (`aluno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_trimestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_trimestre` (
  `id_trimestre` INT NOT NULL,
  `trimestre` VARCHAR(45) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `ano_lectivo_id` INT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  PRIMARY KEY (`id_trimestre`, `ano_lectivo_id`),
  INDEX `fk_tbl_trimestre_tbl_ano_lectivo1_idx` (`ano_lectivo_id` ASC) VISIBLE,
  UNIQUE INDEX `data_inicio_UNIQUE` (`data_inicio` ASC) VISIBLE,
  UNIQUE INDEX `data_fim_UNIQUE` (`data_fim` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_trimestre_tbl_ano_lectivo1`
    FOREIGN KEY (`ano_lectivo_id`)
    REFERENCES `sige_ipial`.`tbl_ano_lectivo` (`ano_lectivo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_nota` (
  `nota_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_avaliacao` DATE NOT NULL,
  `nota_aluno` DOUBLE NOT NULL,
  `tipo_prova` ENUM('AvaliacaoContinua', 'Prova Professor', 'ProvaTrimestre', 'Prova Global', 'Recurso', 'Exame Recurso', 'Exame', 'Exame Especial') NOT NULL,
  `descricao_nota` LONGTEXT NULL,
  `aluno_id` INT NOT NULL,
  `disciplina_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `update_at` TIMESTAMP NOT NULL,
  `id_trimestre` INT NOT NULL,
  PRIMARY KEY (`nota_id`, `aluno_id`, `disciplina_id`, `id_trimestre`),
  INDEX `fk_tbl_nota_tbl_aluno1_idx` (`aluno_id` ASC) VISIBLE,
  INDEX `fk_tbl_nota_tbl_disciplina1_idx` (`disciplina_id` ASC) VISIBLE,
  INDEX `fk_tbl_nota_tbl_trimestre1_idx` (`id_trimestre` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_nota_tbl_aluno1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `sige_ipial`.`tbl_aluno` (`aluno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_nota_tbl_disciplina1`
    FOREIGN KEY (`disciplina_id`)
    REFERENCES `sige_ipial`.`tbl_disciplina` (`disciplina_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_nota_tbl_trimestre1`
    FOREIGN KEY (`id_trimestre`)
    REFERENCES `sige_ipial`.`tbl_trimestre` (`id_trimestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_assiduidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_assiduidade` (
  `assiduidade_id` INT NOT NULL,
  `falta_aluno` TINYINT NOT NULL,
  `status_falta` ENUM('JUSTIFICADA', 'N-JUSTIFICADA') NOT NULL,
  `descricao_falta` LONGTEXT NULL,
  `tipo_falta` ENUM('Disciplinar', 'Presencial') NOT NULL,
  `aluno_id` INT NOT NULL,
  `id_trimestre` INT NOT NULL,
  PRIMARY KEY (`assiduidade_id`, `aluno_id`, `id_trimestre`),
  INDEX `fk_tbl_assiduidade_aluno_tbl_aluno1_idx` (`aluno_id` ASC) VISIBLE,
  INDEX `fk_tbl_assiduidade_tbl_trimestre1_idx` (`id_trimestre` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_assiduidade_aluno_tbl_aluno1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `sige_ipial`.`tbl_aluno` (`aluno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_assiduidade_tbl_trimestre1`
    FOREIGN KEY (`id_trimestre`)
    REFERENCES `sige_ipial`.`tbl_trimestre` (`id_trimestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(455) NOT NULL,
  `password` VARCHAR(65) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `status_usuario` TINYINT NOT NULL,
  `cargo_usuario` ENUM('Professor', 'Aluno', 'Director', 'Subdirector', 'Secretaria', 'Coordenacao', 'Administrador') NOT NULL,
  `imagem_usuario` VARCHAR(65) NULL,
  `created_at` TIMESTAMP NOT NULL,
  `update_at` TIMESTAMP NOT NULL,
  `cod_rec` INT NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `pessoa_id`),
  UNIQUE INDEX `nome_usuario_UNIQUE` (`nome_usuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuarios_pessoas1_idx` (`pessoa_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_pessoas1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `sige_ipial`.`tbl_pessoa` (`pessoa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_encarregado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_encarregado` (
  `encarregado_id` INT NOT NULL AUTO_INCREMENT,
  `grau_parentensco_enc` ENUM('Pai', 'Mãe', 'Tio', 'Tia', 'Outro(a)') NOT NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`encarregado_id`, `pessoa_id`),
  INDEX `fk_tbl_encarregado_tbl_pessoa1_idx` (`pessoa_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_encarregado_tbl_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `sige_ipial`.`tbl_pessoa` (`pessoa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_telefone` (
  `telefone_id` INT NOT NULL AUTO_INCREMENT,
  `num_tel` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `update_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`telefone_id`, `pessoa_id`),
  INDEX `fk_tbl_telefone_tbl_pessoa1_idx` (`pessoa_id` ASC) VISIBLE,
  UNIQUE INDEX `num_tel_UNIQUE` (`num_tel` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_telefone_tbl_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `sige_ipial`.`tbl_pessoa` (`pessoa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_turno` (
  `turno_id` INT NOT NULL AUTO_INCREMENT,
  `nome_turno` ENUM('Manhã', 'Tarde', 'Noite') NOT NULL,
  PRIMARY KEY (`turno_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_tempo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_tempo` (
  `tempo_id` INT NOT NULL AUTO_INCREMENT,
  `tempo` INT NOT NULL,
  PRIMARY KEY (`tempo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_hora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_hora` (
  `hora_id` INT NOT NULL AUTO_INCREMENT,
  `hora` VARCHAR(45) NOT NULL,
  `tempo_id` INT NOT NULL,
  `turno_id` INT NOT NULL,
  PRIMARY KEY (`hora_id`, `tempo_id`, `turno_id`),
  INDEX `fk_tbl_hora_tbl_tempo1_idx` (`tempo_id` ASC) VISIBLE,
  INDEX `fk_horas_turnos1_idx` (`turno_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_hora_tbl_tempo1`
    FOREIGN KEY (`tempo_id`)
    REFERENCES `sige_ipial`.`tbl_tempo` (`tempo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horas_turnos1`
    FOREIGN KEY (`turno_id`)
    REFERENCES `sige_ipial`.`tbl_turno` (`turno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_dia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_dia` (
  `dia_id` INT NOT NULL AUTO_INCREMENT,
  `nome_dia` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`dia_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`professor_leciona_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`professor_leciona_disciplina` (
  `prof_disc_id` INT NOT NULL AUTO_INCREMENT,
  `disciplina_id` INT NOT NULL,
  `professor_id` INT NOT NULL,
  `ano_lectivo_id` INT NOT NULL,
  `prioridade` INT(1) NOT NULL,
  PRIMARY KEY (`prof_disc_id`, `disciplina_id`, `professor_id`, `ano_lectivo_id`),
  INDEX `fk_tbl_prof_leciona_disciplina_tbl_disciplina1_idx` (`disciplina_id` ASC) VISIBLE,
  INDEX `fk_tbl_prof_leciona_disciplina_tbl_professor1_idx` (`professor_id` ASC) VISIBLE,
  INDEX `fk_tbl_professor_disciplina_tbl_ano_lectivo1_idx` (`ano_lectivo_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_prof_leciona_disciplina_tbl_disciplina1`
    FOREIGN KEY (`disciplina_id`)
    REFERENCES `sige_ipial`.`tbl_disciplina` (`disciplina_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_prof_leciona_disciplina_tbl_professor1`
    FOREIGN KEY (`professor_id`)
    REFERENCES `sige_ipial`.`tbl_professor` (`professor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_professor_disciplina_tbl_ano_lectivo1`
    FOREIGN KEY (`ano_lectivo_id`)
    REFERENCES `sige_ipial`.`tbl_ano_lectivo` (`ano_lectivo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`classe_tem_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`classe_tem_disciplina` (
  `classe_disciplina_id` INT NOT NULL AUTO_INCREMENT,
  `carga_horaria` INT NOT NULL,
  `disciplina_id` INT NOT NULL,
  `classe_id` INT NOT NULL,
  PRIMARY KEY (`classe_disciplina_id`, `disciplina_id`, `classe_id`),
  INDEX `fk_tbl_disciplina_pertence_classe_tbl_disciplina1_idx` (`disciplina_id` ASC) VISIBLE,
  INDEX `fk_tbl_disciplina_pertence_classe_tbl_classe1_idx` (`classe_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_disciplina_pertence_classe_tbl_disciplina1`
    FOREIGN KEY (`disciplina_id`)
    REFERENCES `sige_ipial`.`tbl_disciplina` (`disciplina_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_disciplina_pertence_classe_tbl_classe1`
    FOREIGN KEY (`classe_id`)
    REFERENCES `sige_ipial`.`tbl_classe` (`classe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_horario` (
  `tempoDia_id` INT NOT NULL AUTO_INCREMENT,
  `disciplina_id` INT NOT NULL,
  `tempo_id` INT NOT NULL,
  `dia_id` INT NOT NULL,
  `id_turma` INT NOT NULL,
  `sala_id` INT NOT NULL,
  PRIMARY KEY (`tempoDia_id`, `disciplina_id`, `tempo_id`, `dia_id`, `id_turma`, `sala_id`),
  INDEX `fk_tbl_tempo_dia_tbl_disciplina1_idx` (`disciplina_id` ASC) VISIBLE,
  INDEX `fk_tbl_tempo_dia_tbl_tempo1_idx` (`tempo_id` ASC) VISIBLE,
  INDEX `fk_tbl_tempo_dia_tbl_dia1_idx` (`dia_id` ASC) VISIBLE,
  INDEX `fk_tbl_tempo_dia_tbl_turma1_idx` (`id_turma` ASC) VISIBLE,
  INDEX `fk_tbl_tempo_dia_tbl_sala1_idx` (`sala_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_tempo_dia_tbl_disciplina1`
    FOREIGN KEY (`disciplina_id`)
    REFERENCES `sige_ipial`.`tbl_disciplina` (`disciplina_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_tempo_dia_tbl_tempo1`
    FOREIGN KEY (`tempo_id`)
    REFERENCES `sige_ipial`.`tbl_tempo` (`tempo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_tempo_dia_tbl_dia1`
    FOREIGN KEY (`dia_id`)
    REFERENCES `sige_ipial`.`tbl_dia` (`dia_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_tempo_dia_tbl_turma1`
    FOREIGN KEY (`id_turma`)
    REFERENCES `sige_ipial`.`tbl_turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_tempo_dia_tbl_sala1`
    FOREIGN KEY (`sala_id`)
    REFERENCES `sige_ipial`.`tbl_sala` (`sala_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`ano_turma_coord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`ano_turma_coord` (
  `turmaAno_id` INT NOT NULL AUTO_INCREMENT,
  `turma_id` INT NOT NULL,
  `num_vagas` INT NOT NULL,
  `professor_id` INT NOT NULL,
  `ano_lectivo_id` INT NOT NULL,
  PRIMARY KEY (`turmaAno_id`, `turma_id`, `professor_id`, `ano_lectivo_id`),
  INDEX `fk_aluno_turma_coord_tbl_turma1_idx` (`turma_id` ASC) VISIBLE,
  INDEX `fk_ano_turma_coord_professores1_idx` (`professor_id` ASC) VISIBLE,
  INDEX `fk_ano_turma_coord_anos_lectivo1_idx` (`ano_lectivo_id` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_turma_coord_tbl_turma1`
    FOREIGN KEY (`turma_id`)
    REFERENCES `sige_ipial`.`tbl_turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ano_turma_coord_professores1`
    FOREIGN KEY (`professor_id`)
    REFERENCES `sige_ipial`.`tbl_professor` (`professor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ano_turma_coord_anos_lectivo1`
    FOREIGN KEY (`ano_lectivo_id`)
    REFERENCES `sige_ipial`.`tbl_ano_lectivo` (`ano_lectivo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`aluno_pertence_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`aluno_pertence_turma` (
  `aluno_turma_id` INT NOT NULL AUTO_INCREMENT,
  `aluno_id` INT NOT NULL,
  `ano_coord_id` INT NOT NULL,
  PRIMARY KEY (`aluno_turma_id`, `aluno_id`, `ano_coord_id`),
  INDEX `fk_tbl_aluno_turma_tbl_aluno1_idx` (`aluno_id` ASC) VISIBLE,
  INDEX `fk_tbl_aluno_turma_ano_turma_coord1_idx` (`ano_coord_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_aluno_turma_tbl_aluno1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `sige_ipial`.`tbl_aluno` (`aluno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_aluno_turma_ano_turma_coord1`
    FOREIGN KEY (`ano_coord_id`)
    REFERENCES `sige_ipial`.`ano_turma_coord` (`turmaAno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`candidato_seleciona_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`candidato_seleciona_curso` (
  `candidato_id` INT NOT NULL,
  `curso_id` INT NOT NULL,
  `preferencia` INT NOT NULL,
  PRIMARY KEY (`candidato_id`, `curso_id`),
  INDEX `fk_tbl_candidato_has_tbl_curso_tbl_curso2_idx` (`curso_id` ASC) VISIBLE,
  INDEX `fk_tbl_candidato_has_tbl_curso_tbl_candidato2_idx` (`candidato_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_candidato_has_tbl_curso_tbl_candidato2`
    FOREIGN KEY (`candidato_id`)
    REFERENCES `sige_ipial`.`tbl_candidato` (`candidato_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_candidato_has_tbl_curso_tbl_curso2`
    FOREIGN KEY (`curso_id`)
    REFERENCES `sige_ipial`.`tbl_curso` (`curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_comunicado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_comunicado` (
  `id_comunicado` INT NOT NULL AUTO_INCREMENT,
  `titulo_com` VARCHAR(200) NOT NULL,
  `conteudo_com` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `update_at` TIMESTAMP NOT NULL,
  `pessoa_id` INT NOT NULL,
  `ano_lectivo_id` INT NOT NULL,
  PRIMARY KEY (`id_comunicado`, `pessoa_id`, `ano_lectivo_id`),
  INDEX `fk_tbl_comunicado_tbl_pessoa1_idx` (`pessoa_id` ASC) VISIBLE,
  INDEX `fk_comunicados_anos_lectivo1_idx` (`ano_lectivo_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_comunicado_tbl_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `sige_ipial`.`tbl_pessoa` (`pessoa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comunicados_anos_lectivo1`
    FOREIGN KEY (`ano_lectivo_id`)
    REFERENCES `sige_ipial`.`tbl_ano_lectivo` (`ano_lectivo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`tbl_calendario_prova`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`tbl_calendario_prova` (
  `calendario_id` INT NOT NULL AUTO_INCREMENT,
  `inicio_prova` DATE NOT NULL,
  `fim_prova` DATE NOT NULL,
  `tipo_prova` ENUM('Prova Professor', 'ProvaTrimestre', 'Prova Global', 'Recurso', 'Exame Recurso', 'Exame', 'Exame Especial') NOT NULL,
  `classe_id` INT NOT NULL,
  `curso_id` INT NOT NULL,
  `turno_id` INT NOT NULL,
  `id_trimestre` INT NULL,
  PRIMARY KEY (`calendario_id`, `classe_id`, `curso_id`, `turno_id`),
  INDEX `fk_tbl_calendario_tbl_classe1_idx` (`classe_id` ASC) VISIBLE,
  INDEX `fk_tbl_calendario_tbl_curso1_idx` (`curso_id` ASC) VISIBLE,
  INDEX `fk_tbl_calendario_tbl_turno1_idx` (`turno_id` ASC) VISIBLE,
  INDEX `fk_tbl_calendario_tbl_trimestre1_idx` (`id_trimestre` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_calendario_tbl_classe1`
    FOREIGN KEY (`classe_id`)
    REFERENCES `sige_ipial`.`tbl_classe` (`classe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_calendario_tbl_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `sige_ipial`.`tbl_curso` (`curso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_calendario_tbl_turno1`
    FOREIGN KEY (`turno_id`)
    REFERENCES `sige_ipial`.`tbl_turno` (`turno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_calendario_tbl_trimestre1`
    FOREIGN KEY (`id_trimestre`)
    REFERENCES `sige_ipial`.`tbl_trimestre` (`id_trimestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`programas_calendario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`programas_calendario` (
  `agendaCalendar_id` INT NOT NULL AUTO_INCREMENT,
  `calendario_id` INT NOT NULL,
  `disciplina_id` INT NOT NULL,
  `tempo_id` INT NULL,
  `dia_id` INT NOT NULL,
  PRIMARY KEY (`agendaCalendar_id`, `calendario_id`, `disciplina_id`, `dia_id`),
  INDEX `fk_tbl_agendaCalendario_tbl_calendario1_idx` (`calendario_id` ASC) VISIBLE,
  INDEX `fk_tbl_agendaCalendario_tbl_disciplina1_idx` (`disciplina_id` ASC) VISIBLE,
  INDEX `fk_tbl_agendaCalendario_tbl_tempo1_idx` (`tempo_id` ASC) VISIBLE,
  INDEX `fk_tbl_agendaCalendario_tbl_dia1_idx` (`dia_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_agendaCalendario_tbl_calendario1`
    FOREIGN KEY (`calendario_id`)
    REFERENCES `sige_ipial`.`tbl_calendario_prova` (`calendario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_agendaCalendario_tbl_disciplina1`
    FOREIGN KEY (`disciplina_id`)
    REFERENCES `sige_ipial`.`tbl_disciplina` (`disciplina_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_agendaCalendario_tbl_tempo1`
    FOREIGN KEY (`tempo_id`)
    REFERENCES `sige_ipial`.`tbl_tempo` (`tempo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_agendaCalendario_tbl_dia1`
    FOREIGN KEY (`dia_id`)
    REFERENCES `sige_ipial`.`tbl_dia` (`dia_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`turmas_calendario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`turmas_calendario` (
  `turma_agenda_id` INT NOT NULL AUTO_INCREMENT,
  `sala_id` INT NULL,
  `calendario_id` INT NOT NULL,
  `coord_turmaAno_id` INT NULL,
  PRIMARY KEY (`turma_agenda_id`, `calendario_id`),
  INDEX `fk_tbl_turmaAgenda_tbl_sala1_idx` (`sala_id` ASC) VISIBLE,
  INDEX `fk_tbl_turmaAgenda_tbl_calendario1_idx` (`calendario_id` ASC) VISIBLE,
  INDEX `fk_turmas_calendario_ano_turma_coord1_idx` (`coord_turmaAno_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_turmaAgenda_tbl_sala1`
    FOREIGN KEY (`sala_id`)
    REFERENCES `sige_ipial`.`tbl_sala` (`sala_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_turmaAgenda_tbl_calendario1`
    FOREIGN KEY (`calendario_id`)
    REFERENCES `sige_ipial`.`tbl_calendario_prova` (`calendario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turmas_calendario_ano_turma_coord1`
    FOREIGN KEY (`coord_turmaAno_id`)
    REFERENCES `sige_ipial`.`ano_turma_coord` (`turmaAno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`aluno_tem_encarregado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`aluno_tem_encarregado` (
  `enc_aluno_id` INT NOT NULL AUTO_INCREMENT,
  `aluno_id` INT NOT NULL,
  `encarregado_id` INT NOT NULL,
  PRIMARY KEY (`enc_aluno_id`, `aluno_id`, `encarregado_id`),
  INDEX `fk_tbl_aluno_has_tbl_encarregado_tbl_encarregado2_idx` (`encarregado_id` ASC) VISIBLE,
  INDEX `fk_tbl_aluno_has_tbl_encarregado_tbl_aluno2_idx` (`aluno_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_aluno_has_tbl_encarregado_tbl_aluno2`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `sige_ipial`.`tbl_aluno` (`aluno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_aluno_has_tbl_encarregado_tbl_encarregado2`
    FOREIGN KEY (`encarregado_id`)
    REFERENCES `sige_ipial`.`tbl_encarregado` (`encarregado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sige_ipial`.`turma_estuda_turnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sige_ipial`.`turma_estuda_turnos` (
  `turma_turno_id` INT NOT NULL AUTO_INCREMENT,
  `iturma_id` INT NOT NULL,
  `turno_id` INT NOT NULL,
  PRIMARY KEY (`turma_turno_id`, `iturma_id`, `turno_id`),
  INDEX `fk_turmas_has_turnos_turnos1_idx` (`turno_id` ASC) VISIBLE,
  INDEX `fk_turmas_has_turnos_turmas1_idx` (`iturma_id` ASC) VISIBLE,
  CONSTRAINT `fk_turmas_has_turnos_turmas1`
    FOREIGN KEY (`iturma_id`)
    REFERENCES `sige_ipial`.`tbl_turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turmas_has_turnos_turnos1`
    FOREIGN KEY (`turno_id`)
    REFERENCES `sige_ipial`.`tbl_turno` (`turno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
